systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=18080
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=18080
systemProp.http.nonProxyHosts=localhost|127.0.0.1
org.gradle.jvmargs=-Xms256m -Xmx1536m
org.gradle.daemon=false

# 依赖用了 AndroidX，必须开启这个开关；否则 :app:checkReleaseAarMetadata 会 FAIL
android.useAndroidX=true
android.enableJetifier=false
